In [1]:
a=1
b=2
c=a+b
print(c)

3

In [3]:
a = 1
b = 2
print(f"The value of variable a and b are {a} and {b} respectevely")

The value of variable a and b are 1 and 2 respectevely

In [4]:
a = 10;
b = 20;
print("value of a {} and value of b {}".format(a,b))
print("value of a {} and value of b {}".format(b,a))
print("value of a {1} and value of b {0}".format(b,a)) #indexing
print(a,b)

value of a 10 and value of b 20
value of a 20 and value of b 10
value of a 10 and value of b 20
10 20

In [6]:
#string value
my = "country";
name_is = "India"
print("I love my {1} , name_is {0}".format(name_is,my))

I love my country , name_is India

In [7]:
#print without reference variable or pass by value 
print("my name is {},{} from {}".format("Bill","Gate","Microsoft"))

my name is Bill,Gate from Microsoft

In [9]:
#input enter by user

num = input ("Enter a value : ")
print(num)

Enter a value :  Ajin

Ajin

In [10]:
num = input (" ENTER A NUMBER : ");
print(num);

 ENTER A NUMBER :  10

10

In [11]:
#enter multiple value
x= input("Enter 1st digit of PIN no: "),input("Enter 2nd digit of PIN no: "),input("Enter 3rd digit of PIN no: "),input("Enter 4rth digit of PIN no: ")
print(x)

Enter 1st digit of PIN no:  1
Enter 2nd digit of PIN no:  2
Enter 3rd digit of PIN no:  3
Enter 4rth digit of PIN no:  4

('1', '2', '3', '4')

# OPERATORS

In [16]:
#Logical Operators
a = True
b = False
print(not b)

True

In [17]:
#Identity Operators
A = 5
B = 5

print(id(A))
print(id(B))
print(type(A))
print(type(B))
print(A is not B)

140719505920936
140719505920936
<class 'int'>
<class 'int'>
False

In [19]:
L1= [1,2,3]
L2= [1,2,3]

print(id(L1))
print(id(L2))
print(L1 is L2)  #compares address
print(L1 == L2)  #compares values

1654563688448
1654563290240
False
True

In [27]:
# MEMBERSHIP OPERATOR

L1= [1,2,3,4]
print(L1)
print (5 in L1)

[1, 2, 3, 4]
False

In [32]:
x = 10
if (x>0):
    print("x is positive")
else:
    print("x is negative");

x is positive

In [33]:
#case 1

num = 10
if None : #(None, 0 , -1) None : it will not allow to get into loop
    print("number is positive")

print("This will print always") # this will run default

This will print always

In [36]:
#NESTED LOOP
age = 33
if (age>=10 and age<=20):
    print("1st Division");
elif(age>20 and age<=30):
    print("Second Division")
else:
    print("Fail")

Fail

In [39]:
A = 100
B = 20
C = 30

if (A>B and A>C):
    print("A is Biggest")
elif(B>A and B>C):
    print("B is Biggest")
else:
    print("C is biggest")

A is Biggest

In [40]:
a = [10,20,30,40,50]

product = 2

for ele in a:
    product *= ele
    print(product)

20
400
12000
480000
24000000

In [44]:
product = 2
for i in range(10,51,10):
    product *= i
    print(product)
else:
    print("_______________")
    print("End of the loop")

20
400
12000
480000
24000000
_______________
End of the loop

In [45]:
for i in range(2,11,2):
    print(i)

2
4
6
8
10

In [47]:
#odd or even
odd=[]
even=[]
for i in range(1,11):
    if i%2==0:
        even.append(i)
    else:
        odd.append(i)

print(odd)
print(even)

[1, 3, 5, 7, 9]
[2, 4, 6, 8, 10]

In [49]:
#PRIME NUMBER
#FIBONACCI
#REVERESE A STRING
#PALINDROME

In [59]:
#Reverse
s = input("Enter a string: ")
def revstring(s):
    s[::-1]

print("Reversed String is :",revstring(s))

Enter a string:  ki

Reversed String is : None

In [60]:
s= "ajin"
print(s[::-1])

nija

In [66]:
#palindrome
s = "MALAYALAM"
if (s == s[::-1]):
    print("Palindrome String")
else:
    print("Not a Palindrome String")

Palindrome String

In [70]:
n = int(input("Enter a number : "))

if str(n)==str((n)[::-1]):
    print("Palindrome String")
else:
    print("Not a Palindrome String")

Enter a number :  303

TypeError: 'int' object is not subscriptable

In [72]:
def show_name(name):
    """
    this fn shows name
    """
    print("name is " +str(name))

show_name("ajin")

name is ajin

In [85]:
#local variable 

def get_sum(lst):
    """
    this fn will return the sum of elements inside the list
    """
    result = 0
    for num in lst:
        result +=num
        print(result)
    return result

lst1=get_sum([1,2,3,4,5])
print("Sum of the numbers in lst1 is : ",lst1)

1
3
6
10
15
Sum of the numbers in lst1 is :  15

In [14]:
global_var = "This is a global variable"

def global_test():
    local_variable = "this is a local variable"
    global_var="Global variable Inside the function"
    #print(local_variable)
    print(global_var)

print(global_var)

global_test()

This is a global variable
Global variable Inside the function

In [104]:
num1=24
num2=36
while num2!=0:
    remainder=num1%num2
    num1,num2=num2,remainder

print(num2)

0

In [105]:
num = -100
print(abs(num))

100

In [113]:
lst = [1,2,3,4]
lst2 = [0]
print(all(lst))
print(all(lst2))

True
False

In [115]:
lst = []
print(type(lst))
print(dir(lst))
lst2 = tuple(lst)
print(type(lst2))

print(dir(lst2))

<class 'list'>
['__add__', '__class__', '__class_getitem__', '__contains__', '__delattr__', '__delitem__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__imul__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__rmul__', '__setattr__', '__setitem__', '__sizeof__', '__str__', '__subclasshook__', 'append', 'clear', 'copy', 'count', 'extend', 'index', 'insert', 'pop', 'remove', 'reverse', 'sort']
<class 'tuple'>
['__add__', '__class__', '__class_getitem__', '__contains__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getnewargs__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__rmul__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'count', 'index']

In [116]:
#DIVMOD()
#The divmod() method takes two no. & return a pair of no. (a tuple) consisting of their
print(divmod(13,2))

(6, 1)

In [ ]:
#Enumerate()

#this mehtod adds counter to an iterable and returns it
#Syntax enumerate(iterate, start=0) ,ie 10 having position 0, 20 having 1

lst = [10,20,30,40,50]

for index , num in

In [118]:
lst1_list = range(-10,10) #create a list with number from -10 to 10

#print(list(lst1_list))
#print(type(lst1_list))

#lst2_postive

lst2_positive = list(filter(lambda n:n%2 !=0, lst1_list))

#print i in lst2_positive:
for i in lst2_positive:
    print(i)

-9
-7
-5
-3
-1
1
3
5
7
9

In [119]:
#MAP

def hallsquare(num):
    return (num**2)

#using map() function

squared = list(map(lambda x: x **2, [1,2,3,4])) 
print(squared)

[1, 4, 9, 16]

In [122]:
#REDUCE ()

from functools import reduce
lst=[1,2,3,4]
def multiply(x,y):
    return x*y;

product = reduce(lambda x,y: x*y, lst)

print(product)

24

In [123]:
#reduce , It work on double argument , Map work on single argument, filter work on single argument

In [3]:
print("CALCULATOR")
print("Operations")
print("1.Addition,2.Substraction,3.Multiplication,4.Division")
choice=int(input("Enter your choice number : "))

num1=int(input("Enter the first number :"))
num2=int(input("Enter the second number : "))


def addi(num1,num2):
    return num1+num2
def subs(num1,num2):
    return num1-num2;
def multi(num1,num2):
    return num1*num2;
def divi(num1,num2):
    return num1/num2

if choice == 1:
    result=addi(num1,num2)
    print(result)
    #print("Result is : ", lambda x:num1+num2);
    
elif choice ==2 :
    result=subs(num1,num2)
    print(result)
    #print("Result is : ", lambda x:num1-num2);
elif choice == 3:
    result=multi(num1,num2)
    print(result)
    #print("Result is : ", lambda x:num1*num2);
elif choice == 4:
    result=divi(num1,num2)
    print(result)
    #print("Result is : ", lambda x:num1/num2);
else:
    print("Invalid Choice")

CALCULATOR
Operations
1.Addition,2.Substraction,3.Multiplication,4.Division

Enter your choice number :  4
Enter the first number : 3
Enter the second number :  3

1.0

#30/04/2025

In [3]:
#DEFAULT ARGUMENT

#case1
def say(x,y,z):
    prod=x+y+z
    return prod

say(1,2,3)

6

In [16]:
#case 2
def say(x=5,y):    #error
    prod=x+y  
    return prod

say(3)


#when you have first parameter as default we have to give argument values to every parameter

SyntaxError: non-default argument follows default argument (3634045708.py, line 2)

In [13]:
#case3
def say(x,y=5):
    prod= x*y
    return prod

say(1)

5

In [19]:
#case4
def say(x=5,y=5):
    prod = x*y
    return prod

say(6,6)

36

In [22]:
#case5
def say(x,y=4,z=5):
    prod= x*y*z
    return prod

say(1)

20

In [41]:
#case6
def say(x,y=10,z):   #ERROR :non-default argument follows default argument
    prod = x*y*z
    return prod

say(1,z=10)

SyntaxError: non-default argument follows default argument (643731378.py, line 2)

#FILE HANDLING

#import os

In [49]:
import os
os.getcwd()

'C:\\Users\\Administrator'

In [51]:
os.getenv("C:\\Users\\Administrator")  #tell your home directory(os.getcwd)
lst = open("test.txt",'w')  #creates a file on home directory with write mode
lst.write("Hello Ajin Welcome to Banglore \n") #this will write 1st line in file
lst.write("This is second line") #this will write 2nd line in file
lst.close() #always run this command make sure file get back to disk & its safe

In [52]:
lst = open("test.txt", 'r')
lst.read()

'Hello Ajin Welcome to Banglore \nThis is second line'

In [53]:
lst = open("test.txt", 'r')
lst.read(4)

'Hell'

In [56]:
lst = open("test.txt", 'r')
lst.read(8)
lst.read(4)

'in W'

In [55]:
ajin = open("test.txt", 'r')
ajin.tell()

0

In [59]:
ajin = open("test.txt", 'r')
ajin.seek(0)

0

In [60]:
ajin.tell()

0

In [61]:
ajin.seek(5)

5

In [62]:
ajin.tell()

5

In [63]:
ajin.read(10)

' Ajin Welc'

In [64]:
ajin.seek(0)

0

In [65]:
ajin.read(10)

'Hello Ajin'

In [68]:
ajin.seek(0)
for line in ajin:
    print(line)

Hello Ajin Welcome to Banglore

This is second line

In [69]:
ajin.readline()

''

In [72]:
ajin = open("test.txt", 'r')
ajin.readline()

'Hello Ajin Welcome to Banglore \n'

In [78]:
ajin = open("test.txt", 'r')
ajin.readlines()

['Hello Ajin Welcome to Banglore \n', 'This is second line']

In [81]:
ajin.readline()
ajin.close()

In [82]:
#rename
#remove

In [83]:
import os
os.getcwd()

'C:\\Users\\Administrator'

In [84]:
os.getenv('C:\\Users\\Administrator')

In [85]:
os.chdir('C:\\Users\\Administrator')

In [87]:
os.getcwd()

'C:\\Users\\Administrator'

In [88]:
os.listdir(os.getcwdb())

[b'.ipynb_checkpoints',
 b'.ipython',
 b'.jupyter',
 b'.scala_history',
 b'3D Objects',
 b'airflow_venv',
 b'AppData',
 b'Application Data',
 b'Contacts',
 b'Cookies',
 b'Desktop',
 b'Documents',
 b'Downloads',
 b'Favorites',
 b'grafana-server.exe',
 b'Links',
 b'Local Settings',
 b'Music',
 b'My Documents',
 b'NetHood',
 b'NTUSER.DAT',
 b'ntuser.dat.LOG1',
 b'ntuser.dat.LOG2',
 b'NTUSER.DAT{53b39e88-18c4-11ea-a811-000d3aa4692b}.TM.blf',
 b'NTUSER.DAT{53b39e88-18c4-11ea-a811-000d3aa4692b}.TMContainer00000000000000000001.regtrans-ms',
 b'NTUSER.DAT{53b39e88-18c4-11ea-a811-000d3aa4692b}.TMContainer00000000000000000002.regtrans-ms',
 b'ntuser.ini',
 b'OneDrive',
 b'Pictures',
 b'PrintHood',
 b'Recent',
 b'Saved Games',
 b'Searches',
 b'SendTo',
 b'Start Menu',
 b'Templates',
 b'test.txt',
 b'Untitled.ipynb',
 b'untitled.py',
 b'Untitled1.ipynb',
 b'Untitled2.ipynb',
 b'Videos']

In [91]:
ajin = open("test.txt",'r')
ajin.rename("test.txt","newtest.txt")

AttributeError: '_io.TextIOWrapper' object has no attribute 'rename'

In [92]:
os.getcwd()

'C:\\Users\\Administrator'

In [93]:
os.mkdir('AJIN')

In [94]:
os.listdir(os.getcwdb())

[b'.ipynb_checkpoints',
 b'.ipython',
 b'.jupyter',
 b'.scala_history',
 b'3D Objects',
 b'airflow_venv',
 b'AJIN',
 b'AppData',
 b'Application Data',
 b'Contacts',
 b'Cookies',
 b'Desktop',
 b'Documents',
 b'Downloads',
 b'Favorites',
 b'grafana-server.exe',
 b'Links',
 b'Local Settings',
 b'Music',
 b'My Documents',
 b'NetHood',
 b'NTUSER.DAT',
 b'ntuser.dat.LOG1',
 b'ntuser.dat.LOG2',
 b'NTUSER.DAT{53b39e88-18c4-11ea-a811-000d3aa4692b}.TM.blf',
 b'NTUSER.DAT{53b39e88-18c4-11ea-a811-000d3aa4692b}.TMContainer00000000000000000001.regtrans-ms',
 b'NTUSER.DAT{53b39e88-18c4-11ea-a811-000d3aa4692b}.TMContainer00000000000000000002.regtrans-ms',
 b'ntuser.ini',
 b'OneDrive',
 b'Pictures',
 b'PrintHood',
 b'Recent',
 b'Saved Games',
 b'Searches',
 b'SendTo',
 b'Start Menu',
 b'Templates',
 b'test.txt',
 b'Untitled.ipynb',
 b'untitled.py',
 b'Untitled1.ipynb',
 b'Untitled2.ipynb',
 b'Videos']

In [95]:
os.chdir('C:\\Users\\Administrator\\AJIN')

In [96]:
os.getcwd()

'C:\\Users\\Administrator\\AJIN'

In [104]:
os.getenv('C:\\Users\\Administrator\\AJIN')
new = open("newfile.txt",'w')
new.write("Hello this is an assignment")

27

In [109]:
import shutil

os.chdir("C:\\Users\\Administrator\\AJIN")
ajin = open("newfile.txt",'r')
ajin.read()

'Hello this is an assignment'

In [118]:
ajin.close()

In [119]:
os.getcwd()

'C:\\Users\\Administrator'

In [120]:
os.chdir("C:\\Users\\Administrator")

In [124]:
os.listdir(os.getcwdb())

[b'.ipynb_checkpoints',
 b'.ipython',
 b'.jupyter',
 b'.scala_history',
 b'3D Objects',
 b'airflow_venv',
 b'AJIN',
 b'AppData',
 b'Application Data',
 b'Contacts',
 b'Cookies',
 b'Desktop',
 b'Documents',
 b'Downloads',
 b'Favorites',
 b'grafana-server.exe',
 b'Links',
 b'Local Settings',
 b'Music',
 b'My Documents',
 b'NetHood',
 b'NTUSER.DAT',
 b'ntuser.dat.LOG1',
 b'ntuser.dat.LOG2',
 b'NTUSER.DAT{53b39e88-18c4-11ea-a811-000d3aa4692b}.TM.blf',
 b'NTUSER.DAT{53b39e88-18c4-11ea-a811-000d3aa4692b}.TMContainer00000000000000000001.regtrans-ms',
 b'NTUSER.DAT{53b39e88-18c4-11ea-a811-000d3aa4692b}.TMContainer00000000000000000002.regtrans-ms',
 b'ntuser.ini',
 b'OneDrive',
 b'Pictures',
 b'PrintHood',
 b'Recent',
 b'Saved Games',
 b'Searches',
 b'SendTo',
 b'Start Menu',
 b'Templates',
 b'test.txt',
 b'Untitled.ipynb',
 b'untitled.py',
 b'Untitled1.ipynb',
 b'Untitled2.ipynb',
 b'Videos']

In [125]:
shutil.rmtree('AJIN')

PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'AJIN\\newfile.txt'

In [127]:
os.mkdir('NEWDIR')

In [128]:
os.listdir(os.getcwdb())

[b'.ipynb_checkpoints',
 b'.ipython',
 b'.jupyter',
 b'.scala_history',
 b'3D Objects',
 b'airflow_venv',
 b'AJIN',
 b'AppData',
 b'Application Data',
 b'Contacts',
 b'Cookies',
 b'Desktop',
 b'Documents',
 b'Downloads',
 b'Favorites',
 b'grafana-server.exe',
 b'Links',
 b'Local Settings',
 b'Music',
 b'My Documents',
 b'NetHood',
 b'NEWDIR',
 b'NTUSER.DAT',
 b'ntuser.dat.LOG1',
 b'ntuser.dat.LOG2',
 b'NTUSER.DAT{53b39e88-18c4-11ea-a811-000d3aa4692b}.TM.blf',
 b'NTUSER.DAT{53b39e88-18c4-11ea-a811-000d3aa4692b}.TMContainer00000000000000000001.regtrans-ms',
 b'NTUSER.DAT{53b39e88-18c4-11ea-a811-000d3aa4692b}.TMContainer00000000000000000002.regtrans-ms',
 b'ntuser.ini',
 b'OneDrive',
 b'Pictures',
 b'PrintHood',
 b'Recent',
 b'Saved Games',
 b'Searches',
 b'SendTo',
 b'Start Menu',
 b'Templates',
 b'test.txt',
 b'Untitled.ipynb',
 b'untitled.py',
 b'Untitled1.ipynb',
 b'Untitled2.ipynb',
 b'Videos']

In [131]:
os.chdir('C:\\Users\\Administrator\\NEWDIR')

In [132]:
os.getcwd()

'C:\\Users\\Administrator\\NEWDIR'

In [136]:
import shutil

os.chdir('C:\\Users\\Administrator\\NEWDIR')
ajin = open("test.txt","w")
ajin.write("this is 1st module\n")
ajin.close()

In [137]:
ajin = open("test.txt","r")
ajin.read()

'this is 1st module\n'

In [138]:
ajin.close()

In [140]:
os.getcwd()

'C:\\Users\\Administrator\\NEWDIR'

In [141]:
os.chdir("C:\\Users\\Administrator")

In [142]:
os.getcwd()

'C:\\Users\\Administrator'

In [143]:
shutil.rmtree('C:\\Users\\Administrator\\NEWDIR')

In [145]:
os.listdir(os.getcwdb())

[b'.ipynb_checkpoints',
 b'.ipython',
 b'.jupyter',
 b'.scala_history',
 b'3D Objects',
 b'airflow_venv',
 b'AJIN',
 b'AppData',
 b'Application Data',
 b'Contacts',
 b'Cookies',
 b'Desktop',
 b'Documents',
 b'Downloads',
 b'Favorites',
 b'grafana-server.exe',
 b'Links',
 b'Local Settings',
 b'Music',
 b'My Documents',
 b'NetHood',
 b'NTUSER.DAT',
 b'ntuser.dat.LOG1',
 b'ntuser.dat.LOG2',
 b'NTUSER.DAT{53b39e88-18c4-11ea-a811-000d3aa4692b}.TM.blf',
 b'NTUSER.DAT{53b39e88-18c4-11ea-a811-000d3aa4692b}.TMContainer00000000000000000001.regtrans-ms',
 b'NTUSER.DAT{53b39e88-18c4-11ea-a811-000d3aa4692b}.TMContainer00000000000000000002.regtrans-ms',
 b'ntuser.ini',
 b'OneDrive',
 b'Pictures',
 b'PrintHood',
 b'Recent',
 b'Saved Games',
 b'Searches',
 b'SendTo',
 b'Start Menu',
 b'Templates',
 b'test.txt',
 b'Untitled.ipynb',
 b'untitled.py',
 b'Untitled1.ipynb',
 b'Untitled2.ipynb',
 b'Videos']

In [2]:
dir(__builtins__)

['ArithmeticError',
 'AssertionError',
 'AttributeError',
 'BaseException',
 'BaseExceptionGroup',
 'BlockingIOError',
 'BrokenPipeError',
 'BufferError',
 'BytesWarning',
 'ChildProcessError',
 'ConnectionAbortedError',
 'ConnectionError',
 'ConnectionRefusedError',
 'ConnectionResetError',
 'DeprecationWarning',
 'EOFError',
 'Ellipsis',
 'EncodingWarning',
 'EnvironmentError',
 'Exception',
 'ExceptionGroup',
 'False',
 'FileExistsError',
 'FileNotFoundError',
 'FloatingPointError',
 'FutureWarning',
 'GeneratorExit',
 'IOError',
 'ImportError',
 'ImportWarning',
 'IndentationError',
 'IndexError',
 'InterruptedError',
 'IsADirectoryError',
 'KeyError',
 'KeyboardInterrupt',
 'LookupError',
 'MemoryError',
 'ModuleNotFoundError',
 'NameError',
 'None',
 'NotADirectoryError',
 'NotImplemented',
 'NotImplementedError',
 'OSError',
 'OverflowError',
 'PendingDeprecationWarning',
 'PermissionError',
 'ProcessLookupError',
 'RecursionError',
 'ReferenceError',
 'ResourceWarning',
 'RuntimeError',
 'RuntimeWarning',
 'StopAsyncIteration',
 'StopIteration',
 'SyntaxError',
 'SyntaxWarning',
 'SystemError',
 'SystemExit',
 'TabError',
 'TimeoutError',
 'True',
 'TypeError',
 'UnboundLocalError',
 'UnicodeDecodeError',
 'UnicodeEncodeError',
 'UnicodeError',
 'UnicodeTranslateError',
 'UnicodeWarning',
 'UserWarning',
 'ValueError',
 'Warning',
 'WindowsError',
 'ZeroDivisionError',
 '__IPYTHON__',
 '__build_class__',
 '__debug__',
 '__doc__',
 '__import__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'abs',
 'aiter',
 'all',
 'anext',
 'any',
 'ascii',
 'bin',
 'bool',
 'breakpoint',
 'bytearray',
 'bytes',
 'callable',
 'chr',
 'classmethod',
 'compile',
 'complex',
 'copyright',
 'credits',
 'delattr',
 'dict',
 'dir',
 'display',
 'divmod',
 'enumerate',
 'eval',
 'exec',
 'execfile',
 'filter',
 'float',
 'format',
 'frozenset',
 'get_ipython',
 'getattr',
 'globals',
 'hasattr',
 'hash',
 'help',
 'hex',
 'id',
 'input',
 'int',
 'isinstance',
 'issubclass',
 'iter',
 'len',
 'license',
 'list',
 'locals',
 'map',
 'max',
 'memoryview',
 'min',
 'next',
 'object',
 'oct',
 'open',
 'ord',
 'pow',
 'print',
 'property',
 'range',
 'repr',
 'reversed',
 'round',
 'runfile',
 'set',
 'setattr',
 'slice',
 'sorted',
 'staticmethod',
 'str',
 'sum',
 'super',
 'tuple',
 'type',
 'vars',
 'zip']

In [5]:
#import module sys to get the type of exception
import sys

lst = ['b',0,2]
for entry in lst:
    try:
        print("value is:",entry)
        k = 1/int(entry)

    except:
        print("oops" , sys.exc_info(),"occured");
        print("next entry")

print("The reciprocal of", entry ,"is" , k)

value is: b
oops (<class 'ValueError'>, ValueError("invalid literal for int() with base 10: 'b'"), <traceback object at 0x000001D0874811C0>) occured
next entry
value is: 0
oops (<class 'ZeroDivisionError'>, ZeroDivisionError('division by zero'), <traceback object at 0x000001D087481140>) occured
next entry
value is: 2
The reciprocal of 2 is 0.5

In [7]:
import sys

lst = ['b',0,2]

for entry in lst:
    try:
        print("Value is ",entry)
        k = 1/int(entry)
    except(ValueError):
        print("Value Error Occured")
    except(ZeroDivisionError):
        print("Cant Divide by zero")
    except:
        print("Other error")

print("The reciprocal of ",entry ,"is", k)

Value is  b
Value Error Occured
Value is  0
Cant Divide by zero
Value is  2
The reciprocal of  2 is 0.5

In [9]:
import os
os.getcwd()

'C:\\Users\\Administrator'

In [11]:
import os
os.chdir('C:\\Users\\Administrator')
try:
    f = open('prwa.txt')
    #perform file operation


finally:
    print("final closed")
    f.close()

final closed

NameError: name 'f' is not defined

In [16]:
import sys
import logging
logging.basicConfig(level=logging.INFO)
try:
    f = open('prwa.txt')
    #perform file operation

except:
    #print('Something went wrong');
    logging.info(sys.exc_info())

INFO:root:(<class 'FileNotFoundError'>, FileNotFoundError(2, 'No such file or directory'), <traceback object at 0x0000028F8779A480>)

In [2]:
import logging
logging.basicConfig(level=logging.INFO)
logging.debug("This is a debug message")

In [17]:
import os 
os.getcwd()

'C:\\Users\\Administrator'

In [24]:
pip install pandas

Requirement already satisfied: pandas in c:\program files\python311\lib\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.23.2 in c:\program files\python311\lib\site-packages (from pandas) (2.2.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\program files\python311\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\program files\python311\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\program files\python311\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\program files\python311\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip available: 22.3 -> 25.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [70]:

import pandas as pd

jk = pd.read_csv('nyc_weather.csv')
jk.head(10)
#jk.tail(10)
jk

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
0,1/1/2016,38,23,52,30.03,10,8.0,0,5,NaN,281
1,1/2/2016,36,18,46,30.02,10,7.0,0,3,NaN,275
2,1/3/2016,40,21,47,29.86,10,8.0,0,1,NaN,277
3,1/4/2016,25,9,44,30.05,10,9.0,0,3,NaN,345
4,1/5/2016,20,-3,41,30.57,10,5.0,0,0,NaN,333
5,1/6/2016,33,4,35,30.50,10,4.0,0,0,NaN,259
6,1/7/2016,39,11,33,30.28,10,2.0,0,3,NaN,293
7,1/8/2016,39,29,64,30.20,10,4.0,0,8,NaN,79
8,1/9/2016,44,38,77,30.16,9,8.0,T,8,Rain,76
9,1/10/2016,50,46,71,29.59,4,NaN,1.8,7,Rain,109
10,1/11/2016,33,8,37,29.92,10,NaN,0,1,NaN,289
11,1/12/2016,35,15,53,29.85,10,6.0,T,4,NaN,235
12,1/13/2016,26,4,42,29.94,10,10.0,0,0,NaN,284
13,1/14/2016,30,12,47,29.95,10,5.0,T,7,NaN,266
14,1/15/2016,43,31,62,29.82,9,5.0,T,2,NaN,101
15,1/16/2016,47,37,70,29.52,8,7.0,0.24,7,Rain,340
16,1/17/2016,36,23,66,29.78,8,6.0,0.05,6,Fog-Snow,345
17,1/18/2016,25,6,53,29.83,9,12.0,T,2,Snow,293
18,1/19/2016,22,3,42,30.03,10,11.0,0,1,NaN,293
19,1/20/2016,32,15,49,30.13,10,6.0,0,2,NaN,302
20,1/21/2016,31,11,45,30.15,10,6.0,0,1,NaN,312
21,1/22/2016,26,6,41,30.21,9,NaN,0.01,3,Snow,34
22,1/23/2016,26,21,78,29.77,1,16.0,2.31,8,Fog-Snow,42
23,1/24/2016,28,11,53,29.92,8,6.0,T,3,Snow,327
24,1/25/2016,34,18,54,30.25,10,3.0,0,2,NaN,286
25,1/26/2016,43,29,56,30.03,10,7.0,0,2,NaN,244
26,1/27/2016,41,22,45,30.03,10,7.0,T,3,Rain,311
27,1/28/2016,37,20,51,29.90,10,5.0,0,1,NaN,234
28,1/29/2016,36,21,50,29.58,10,8.0,0,4,NaN,298
29,1/30/2016,34,16,46,30.01,10,7.0,0,0,NaN,257
30,1/31/2016,46,28,52,29.90,10,5.0,0,0,NaN,241

In [71]:
#NAN : not a no.

jk.Events.unique()
jk.Humidity

0     52
1     46
2     47
3     44
4     41
5     35
6     33
7     64
8     77
9     71
10    37
11    53
12    42
13    47
14    62
15    70
16    66
17    53
18    42
19    49
20    45
21    41
22    78
23    53
24    54
25    56
26    45
27    51
28    50
29    46
30    52
Name: Humidity, dtype: int64

In [35]:
jk.columns

Index(['EST', 'Temperature', 'DewPoint', 'Humidity', 'Sea Level PressureIn',
       'VisibilityMiles', 'WindSpeedMPH', 'PrecipitationIn', 'CloudCover',
       'Events', 'WindDirDegrees'],
      dtype='object')

In [41]:
jk.count() #columnwise record count
#jk.Temperature.count #individual column count
#jk.describe()  #it will give details of matrix

EST                     31
Temperature             31
DewPoint                31
Humidity                31
Sea Level PressureIn    31
VisibilityMiles         31
WindSpeedMPH            28
PrecipitationIn         31
CloudCover              31
Events                   9
WindDirDegrees          31
dtype: int64

In [42]:
jk.describe()

,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,CloudCover,WindDirDegrees
count,31.000000,31.000000,31.000000,31.000000,31.000000,28.000000,31.000000,31.000000
mean,34.677419,17.838710,51.677419,29.992903,9.193548,6.892857,3.129032,247.129032
std,7.639315,11.378626,11.634395,0.237237,1.939405,2.871821,2.629853,92.308086
min,20.000000,-3.000000,33.000000,29.520000,1.000000,2.000000,0.000000,34.000000
25%,29.000000,10.000000,44.500000,29.855000,9.000000,5.000000,1.000000,238.000000
50%,35.000000,18.000000,50.000000,30.010000,10.000000,6.500000,3.000000,281.000000
75%,39.500000,23.000000,55.000000,30.140000,10.000000,8.000000,4.500000,300.000000
max,50.000000,46.000000,78.000000,30.570000,10.000000,16.000000,8.000000,345.000000

In [45]:
jk.shape

(31, 11)

In [46]:
jk.WindSpeedMPH

0      8.0
1      7.0
2      8.0
3      9.0
4      5.0
5      4.0
6      2.0
7      4.0
8      8.0
9      NaN
10     NaN
11     6.0
12    10.0
13     5.0
14     5.0
15     7.0
16     6.0
17    12.0
18    11.0
19     6.0
20     6.0
21     NaN
22    16.0
23     6.0
24     3.0
25     7.0
26     7.0
27     5.0
28     8.0
29     7.0
30     5.0
Name: WindSpeedMPH, dtype: float64

In [48]:
jk.WindSpeedMPH.isna() #row 9,10,21 are NAN

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9      True
10     True
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21     True
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
Name: WindSpeedMPH, dtype: bool

In [50]:
jk.WindSpeedMPH.isna().sum() #will tell you that how many NAN is available in this column

np.int64(3)

In [53]:
jk.dtypes

EST                      object
Temperature               int64
DewPoint                  int64
Humidity                  int64
Sea Level PressureIn    float64
VisibilityMiles           int64
WindSpeedMPH            float64
PrecipitationIn          object
CloudCover                int64
Events                   object
WindDirDegrees            int64
dtype: object

In [54]:
jk.Events.unique

<bound method Series.unique of 0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
5          NaN
6          NaN
7          NaN
8         Rain
9         Rain
10         NaN
11         NaN
12         NaN
13         NaN
14         NaN
15        Rain
16    Fog-Snow
17        Snow
18         NaN
19         NaN
20         NaN
21        Snow
22    Fog-Snow
23        Snow
24         NaN
25         NaN
26        Rain
27         NaN
28         NaN
29         NaN
30         NaN
Name: Events, dtype: object>

In [55]:
jk.Events.describe()

count        9
unique       3
top       Rain
freq         4
Name: Events, dtype: object

In [58]:
#get maximum temperature
print(jk['Temperature'].max())

50

In [59]:
jk['Humidity'].min()

np.int64(33)

In [62]:
jk1 = jk['Temperature'] > 30
jk1
jk1.sum() #total no.of temp more than 30
jk1.head()

0     True
1     True
2     True
3    False
4    False
Name: Temperature, dtype: bool

In [65]:
#To know which day it rains

jk['EST'][jk['Humidity']==70]

15    1/16/2016
Name: EST, dtype: object

In [67]:
jk['EST'][jk['Humidity']>=70]

8      1/9/2016
9     1/10/2016
15    1/16/2016
22    1/23/2016
Name: EST, dtype: object

In [69]:
jk['EST'][jk['WindSpeedMPH']==7.0][jk['Humidity']>=70]

15    1/16/2016
Name: EST, dtype: object

In [72]:
jk

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
0,1/1/2016,38,23,52,30.03,10,8.0,0,5,NaN,281
1,1/2/2016,36,18,46,30.02,10,7.0,0,3,NaN,275
2,1/3/2016,40,21,47,29.86,10,8.0,0,1,NaN,277
3,1/4/2016,25,9,44,30.05,10,9.0,0,3,NaN,345
4,1/5/2016,20,-3,41,30.57,10,5.0,0,0,NaN,333
5,1/6/2016,33,4,35,30.50,10,4.0,0,0,NaN,259
6,1/7/2016,39,11,33,30.28,10,2.0,0,3,NaN,293
7,1/8/2016,39,29,64,30.20,10,4.0,0,8,NaN,79
8,1/9/2016,44,38,77,30.16,9,8.0,T,8,Rain,76
9,1/10/2016,50,46,71,29.59,4,NaN,1.8,7,Rain,109
10,1/11/2016,33,8,37,29.92,10,NaN,0,1,NaN,289
11,1/12/2016,35,15,53,29.85,10,6.0,T,4,NaN,235
12,1/13/2016,26,4,42,29.94,10,10.0,0,0,NaN,284
13,1/14/2016,30,12,47,29.95,10,5.0,T,7,NaN,266
14,1/15/2016,43,31,62,29.82,9,5.0,T,2,NaN,101
15,1/16/2016,47,37,70,29.52,8,7.0,0.24,7,Rain,340
16,1/17/2016,36,23,66,29.78,8,6.0,0.05,6,Fog-Snow,345
17,1/18/2016,25,6,53,29.83,9,12.0,T,2,Snow,293
18,1/19/2016,22,3,42,30.03,10,11.0,0,1,NaN,293
19,1/20/2016,32,15,49,30.13,10,6.0,0,2,NaN,302
20,1/21/2016,31,11,45,30.15,10,6.0,0,1,NaN,312
21,1/22/2016,26,6,41,30.21,9,NaN,0.01,3,Snow,34
22,1/23/2016,26,21,78,29.77,1,16.0,2.31,8,Fog-Snow,42
23,1/24/2016,28,11,53,29.92,8,6.0,T,3,Snow,327
24,1/25/2016,34,18,54,30.25,10,3.0,0,2,NaN,286
25,1/26/2016,43,29,56,30.03,10,7.0,0,2,NaN,244
26,1/27/2016,41,22,45,30.03,10,7.0,T,3,Rain,311
27,1/28/2016,37,20,51,29.90,10,5.0,0,1,NaN,234
28,1/29/2016,36,21,50,29.58,10,8.0,0,4,NaN,298
29,1/30/2016,34,16,46,30.01,10,7.0,0,0,NaN,257
30,1/31/2016,46,28,52,29.90,10,5.0,0,0,NaN,241

In [73]:
jk.Temperature

0     38
1     36
2     40
3     25
4     20
5     33
6     39
7     39
8     44
9     50
10    33
11    35
12    26
13    30
14    43
15    47
16    36
17    25
18    22
19    32
20    31
21    26
22    26
23    28
24    34
25    43
26    41
27    37
28    36
29    34
30    46
Name: Temperature, dtype: int64

In [74]:
jk.head(10)

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
0,1/1/2016,38,23,52,30.03,10,8.0,0,5,NaN,281
1,1/2/2016,36,18,46,30.02,10,7.0,0,3,NaN,275
2,1/3/2016,40,21,47,29.86,10,8.0,0,1,NaN,277
3,1/4/2016,25,9,44,30.05,10,9.0,0,3,NaN,345
4,1/5/2016,20,-3,41,30.57,10,5.0,0,0,NaN,333
5,1/6/2016,33,4,35,30.50,10,4.0,0,0,NaN,259
6,1/7/2016,39,11,33,30.28,10,2.0,0,3,NaN,293
7,1/8/2016,39,29,64,30.20,10,4.0,0,8,NaN,79
8,1/9/2016,44,38,77,30.16,9,8.0,T,8,Rain,76
9,1/10/2016,50,46,71,29.59,4,NaN,1.8,7,Rain,109

In [95]:
lst = [10,20,30,40,50,60]
print(type(lst))
s = pd.Series(lst,index=('1st',2,'2nd',3,'3rd',4))
print(s)

<class 'list'>
1st    10
2      20
2nd    30
3      40
3rd    50
4      60
dtype: int64

In [81]:
l1 = [1,2,3]

ser = pd.Series(l1,index=['1st',2,'3rd'])
print(ser,type(ser))

1st    1
2      2
3rd    3
dtype: int64 <class 'pandas.core.series.Series'>

In [87]:
print(s.loc[0:4])

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [97]:
s = pd.Series(lst,dtype='float32')
print(s,type(s))
s[3]

0    10.0
1    20.0
2    30.0
3    40.0
4    50.0
5    60.0
dtype: float32 <class 'pandas.core.series.Series'>

np.float32(40.0)

In [98]:
s.shape

(6,)

In [103]:
aji = [10,"Ajin",34.56,"DEV"]

s =  pd.Series(aji,index=("RollNo","Name","Marks","Desig"))

print(s,type(s))
s['RollNo']

RollNo       10
Name       Ajin
Marks     34.56
Desig       DEV
dtype: object <class 'pandas.core.series.Series'>

10

In [105]:
d1 = {"sub" : "Python", "sub2" : "Java" , "sub3" : "Data Science"}
print(d1,type(d1))

{'sub': 'Python', 'sub2': 'Java', 'sub3': 'Data Science'} <class 'dict'>

In [106]:
d1.items()

dict_items([('sub', 'Python'), ('sub2', 'Java'), ('sub3', 'Data Science')])

In [107]:
d1.keys()

dict_keys(['sub', 'sub2', 'sub3'])

In [108]:
d1.values()

dict_values(['Python', 'Java', 'Data Science'])

In [109]:
d1["sub"]

'Python'

In [110]:
import numpy as np

In [114]:
num = np.array([1,2,3])
pd.Series(num)

0    1
1    2
2    3
dtype: int64

CREATING AND OBJECT DATAFRAME BY USING LIST/TUPLE

In [115]:
lst = [[1,0,1,3] , [10,20,30,0],[10,20,30,40]]

df = pd.Series(lst)
print(df)

0        [1, 0, 1, 3]
1     [10, 20, 30, 0]
2    [10, 20, 30, 40]
dtype: object

In [116]:
lst = [[10,'RS'],[20,'JG'],[30,'MCK'],[40,'TRA']]

df= pd.DataFrame(lst)

print(df)

    0    1
0  10   RS
1  20   JG
2  30  MCK
3  40  TRA

In [125]:
df.iloc[1:,:]

    0    1
1  20   JG
2  30  MCK
3  40  TRA

In [118]:
df.iloc[3,1]

'TRA'

In [134]:
lst = [[10,'RS'],[20,'JG'],[30,'MCK'],[40,'TRA']]

df = pd.DataFrame(lst, columns=["Rno","Name"],index= [1,2,"three","four"])
print(df)

       Rno Name
1       10   RS
2       20   JG
three   30  MCK
four    40  TRA

In [143]:
tpl = (("Rossum", 75),("Gosling",85),("Travis",65),("Ritche",95),("MCKinney",60))

df = pd.DataFrame(tpl, index=[1,'@',3,4,5],columns =['Name','Age'])

print(df)

       Name  Age
1    Rossum   75
@   Gosling   85
3    Travis   65
4    Ritche   95
5  MCKinney   60

In [144]:
df['salary'] = [1,2,3,4,5]

In [145]:
df

       Name  Age  salary
1    Rossum   75       1
@   Gosling   85       2
3    Travis   65       3
4    Ritche   95       4
5  MCKinney   60       5

In [147]:
df.drop("salary",axis=1,inplace = True)

In [148]:
df

       Name  Age
1    Rossum   75
@   Gosling   85
3    Travis   65
4    Ritche   95
5  MCKinney   60

CREATING AN OBJECT DATAFRAME BY USING DICT OBJECT

In [140]:
dictdata = {"Names":["Rossum","Gosling","Ritche","McKinney"],"Subjects":["Pyhton","Java","C","Pandas"],"Ages":[65,80,85,55] }
#dictdata.values()
print(dictdata)

{'Names': ['Rossum', 'Gosling', 'Ritche', 'McKinney'], 'Subjects': ['Pyhton', 'Java', 'C', 'Pandas'], 'Ages': [65, 80, 85, 55]}

In [141]:
df = pd.DataFrame(dictdata)
print(df)

      Names Subjects  Ages
0    Rossum   Pyhton    65
1   Gosling     Java    80
2    Ritche        C    85
3  McKinney   Pandas    55

In [151]:
df = pd.DataFrame(dictdata)
df.shape

(4, 3)

In [152]:
df = pd.DataFrame(dictdata,index = [1,2,3,'e'])
print(df)

      Names Subjects  Ages
1    Rossum   Pyhton    65
2   Gosling     Java    80
3    Ritche        C    85
e  McKinney   Pandas    55

# CREATING AN OBJECT DATAFRAME USING SERIES OBJECT

In [156]:
l1 = [10,20,30,40,50]

sdata = pd.Series(l1)
print(sdata)

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [159]:
df = pd.DataFrame(sdata , columns = ["number"])
print(df)

   number
0      10
1      20
2      30
3      40
4      50

In [162]:
d1 = {"totmark" : [100,110,120,130],"ExtMarks":[80,75,65,90]}
df = pd.DataFrame(d1,index = [1,2,3,4])
(df)

   totmark  ExtMarks
1      100        80
2      110        75
3      120        65
4      130        90

In [164]:
df.iloc[3:,:]

   totmark  ExtMarks
4      130        90

In [168]:
# ADD NEW COLUMN NAME TO DATAFRAME

df['Sum'] = df['totmark'] + df['ExtMarks']
df

   totmark  ExtMarks  Sum
1      100        80  180
2      110        75  185
3      120        65  185
4      130        90  220

In [167]:
df.drop('c3',axis=1, inplace=True)
df

   totmark  ExtMarks
1      100        80
2      110        75
3      120        65
4      130        90

In [169]:
df

   totmark  ExtMarks  Sum
1      100        80  180
2      110        75  185
3      120        65  185
4      130        90  220

In [170]:
df['New Column'] = [1,2,3,4]

In [171]:
df

   totmark  ExtMarks  Sum  New Column
1      100        80  180           1
2      110        75  185           2
3      120        65  185           3
4      130        90  220           4

In [172]:
df ['sub'] = df['totmark'] - df['ExtMarks']

In [173]:
df

   totmark  ExtMarks  Sum  New Column  sub
1      100        80  180           1   20
2      110        75  185           2   35
3      120        65  185           3   55
4      130        90  220           4   40

In [174]:
df.drop('New Column', axis=1, inplace = True)

In [175]:
df

   totmark  ExtMarks  Sum  sub
1      100        80  180   20
2      110        75  185   35
3      120        65  185   55
4      130        90  220   40

In [176]:
df['New Column'] = [1,2,3,4]
df

   totmark  ExtMarks  Sum  sub  New Column
1      100        80  180   20           1
2      110        75  185   35           2
3      120        65  185   55           3
4      130        90  220   40           4

In [177]:
df ['new data'] = ['1st', '2nd','3rd','4rth']
df

   totmark  ExtMarks  Sum  sub  New Column new data
1      100        80  180   20           1      1st
2      110        75  185   35           2      2nd
3      120        65  185   55           3      3rd
4      130        90  220   40           4     4rth

In [178]:
df['Roll_No'] = range(1,5)

In [179]:
df

   totmark  ExtMarks  Sum  sub  New Column new data  Roll_No
1      100        80  180   20           1      1st        1
2      110        75  185   35           2      2nd        2
3      120        65  185   55           3      3rd        3
4      130        90  220   40           4     4rth        4

In [182]:
#changing the column order
df = df[['Roll_No','totmark','ExtMarks','Sum','New Column','new data']]

In [183]:
df

   Roll_No  totmark  ExtMarks  Sum  New Column new data
1        1      100        80  180           1      1st
2        2      110        75  185           2      2nd
3        3      120        65  185           3      3rd
4        4      130        90  220           4     4rth

# ASSIGNMENT : HW : HOW TO JOIN TWO TABLES USING DATAFRAME

# SORTING THE DATAFRAME DATA

In [184]:
df ['Name'] = ["Ajin","Pradul","Prajual","Sachin"]
df

   Roll_No  totmark  ExtMarks  Sum  New Column new data     Name
1        1      100        80  180           1      1st     Ajin
2        2      110        75  185           2      2nd   Pradul
3        3      120        65  185           3      3rd  Prajual
4        4      130        90  220           4     4rth   Sachin

In [186]:
df = df.sort_values(["Name"],ascending=False)
df

   Roll_No  totmark  ExtMarks  Sum  New Column new data     Name
4        4      130        90  220           4     4rth   Sachin
3        3      120        65  185           3      3rd  Prajual
2        2      110        75  185           2      2nd   Pradul
1        1      100        80  180           1      1st     Ajin

In [188]:
df = df.sort_values(["ExtMarks"],ascending=True)
df

   Roll_No  totmark  ExtMarks  Sum  New Column new data     Name
3        3      120        65  185           3      3rd  Prajual
2        2      110        75  185           2      2nd   Pradul
1        1      100        80  180           1      1st     Ajin
4        4      130        90  220           4     4rth   Sachin

In [195]:
import pandas as pd

df = pd.read_csv('IPL Matches 2008-2020.csv')
df

,id,city,date,player_of_match,venue,neutral_venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,eliminator,method,umpire1,umpire2
0,335982,Bangalore,2008-04-18,BB McCullum,M Chinnaswamy Stadium,0,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,Chandigarh,2008-04-19,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",0,Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,N,NaN,MR Benson,SL Shastri
2,335984,Delhi,2008-04-19,MF Maharoof,Feroz Shah Kotla,0,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,Mumbai,2008-04-20,MV Boucher,Wankhede Stadium,0,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,N,NaN,SJ Davis,DJ Harper
4,335986,Kolkata,2008-04-20,DJ Hussey,Eden Gardens,0,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,N,NaN,BF Bowden,K Hariharan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
811,1216547,Dubai,2020-09-28,AB de Villiers,Dubai International Cricket Stadium,0,Royal Challengers Bangalore,Mumbai Indians,Mumbai Indians,field,Royal Challengers Bangalore,tie,NaN,Y,NaN,Nitin Menon,PR Reiffel
812,1237177,Dubai,2020-11-05,JJ Bumrah,Dubai International Cricket Stadium,0,Mumbai Indians,Delhi Capitals,Delhi Capitals,field,Mumbai Indians,runs,57.0,N,NaN,CB Gaffaney,Nitin Menon
813,1237178,Abu Dhabi,2020-11-06,KS Williamson,Sheikh Zayed Stadium,0,Royal Challengers Bangalore,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Sunrisers Hyderabad,wickets,6.0,N,NaN,PR Reiffel,S Ravi
814,1237180,Abu Dhabi,2020-11-08,MP Stoinis,Sheikh Zayed Stadium,0,Delhi Capitals,Sunrisers Hyderabad,Delhi Capitals,bat,Delhi Capitals,runs,17.0,N,NaN,PR Reiffel,S Ravi
815,1237181,Dubai,2020-11-10,TA Boult,Dubai International Cricket Stadium,0,Delhi Capitals,Mumbai Indians,Delhi Capitals,bat,Mumbai Indians,wickets,5.0,N,NaN,CB Gaffaney,Nitin Menon

In [190]:
#Scientific PY
pip install skipy

Collecting skipy
  Downloading skipy-0.2.3-py3-none-any.whl (8.7 kB)
Collecting boto3<2.0.0,>=1.29.6
  Downloading boto3-1.38.7-py3-none-any.whl (139 kB)
     -------------------------------------- 139.9/139.9 kB 4.1 MB/s eta 0:00:00
Collecting google-api-python-client<3.0.0,>=2.108.0
  Downloading google_api_python_client-2.169.0-py3-none-any.whl (13.3 MB)
     --------------------------------------- 13.3/13.3 MB 10.4 MB/s eta 0:00:00
Collecting python-magic<0.5.0,>=0.4.27
  Downloading python_magic-0.4.27-py2.py3-none-any.whl (13 kB)
Requirement already satisfied: requests<3.0.0,>=2.31.0 in c:\program files\python311\lib\site-packages (from skipy) (2.32.3)
Collecting selenium<5.0.0,>=4.15.2
  Downloading selenium-4.31.0-py3-none-any.whl (9.4 MB)
     ---------------------------------------- 9.4/9.4 MB 12.2 MB/s eta 0:00:00
Collecting slack-sdk<4.0.0,>=3.34.0
  Downloading slack_sdk-3.35.0-py2.py3-none-any.whl (293 kB)
     -------------------------------------- 293.3/293.3 kB 9.1 MB/s eta 0:00:00
Collecting botocore<1.39.0,>=1.38.7
  Downloading botocore-1.38.7-py3-none-any.whl (13.5 MB)
     --------------------------------------- 13.5/13.5 MB 11.3 MB/s eta 0:00:00
Collecting jmespath<2.0.0,>=0.7.1
  Downloading jmespath-1.0.1-py3-none-any.whl (20 kB)
Collecting s3transfer<0.13.0,>=0.12.0
  Downloading s3transfer-0.12.0-py3-none-any.whl (84 kB)
     ---------------------------------------- 84.8/84.8 kB 5.0 MB/s eta 0:00:00
Collecting httplib2<1.0.0,>=0.19.0
  Downloading httplib2-0.22.0-py3-none-any.whl (96 kB)
     ---------------------------------------- 96.9/96.9 kB 5.4 MB/s eta 0:00:00
Collecting google-auth!=2.24.0,!=2.25.0,<3.0.0,>=1.32.0
  Downloading google_auth-2.39.0-py2.py3-none-any.whl (212 kB)
     -------------------------------------- 212.3/212.3 kB 6.5 MB/s eta 0:00:00
Collecting google-auth-httplib2<1.0.0,>=0.2.0
  Downloading google_auth_httplib2-0.2.0-py2.py3-none-any.whl (9.3 kB)
Collecting google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5
  Downloading google_api_core-2.24.2-py3-none-any.whl (160 kB)
     -------------------------------------- 160.1/160.1 kB 9.4 MB/s eta 0:00:00
Collecting uritemplate<5,>=3.0.1
  Downloading uritemplate-4.1.1-py2.py3-none-any.whl (10 kB)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\program files\python311\lib\site-packages (from requests<3.0.0,>=2.31.0->skipy) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in c:\program files\python311\lib\site-packages (from requests<3.0.0,>=2.31.0->skipy) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\program files\python311\lib\site-packages (from requests<3.0.0,>=2.31.0->skipy) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\program files\python311\lib\site-packages (from requests<3.0.0,>=2.31.0->skipy) (2025.1.31)
Collecting trio~=0.17
  Downloading trio-0.30.0-py3-none-any.whl (499 kB)
     -------------------------------------- 499.2/499.2 kB 7.9 MB/s eta 0:00:00
Collecting trio-websocket~=0.9
  Downloading trio_websocket-0.12.2-py3-none-any.whl (21 kB)
Requirement already satisfied: typing_extensions~=4.9 in c:\program files\python311\lib\site-packages (from selenium<5.0.0,>=4.15.2->skipy) (4.13.2)
Requirement already satisfied: websocket-client~=1.8 in c:\program files\python311\lib\site-packages (from selenium<5.0.0,>=4.15.2->skipy) (1.8.0)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in c:\program files\python311\lib\site-packages (from botocore<1.39.0,>=1.38.7->boto3<2.0.0,>=1.29.6->skipy) (2.9.0.post0)
Requirement already satisfied: googleapis-common-protos<2.0.0,>=1.56.2 in c:\program files\python311\lib\site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client<3.0.0,>=2.108.0->skipy) (1.70.0)
Requirement already satisfied: protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<7.0.0,>=3.19.5 in c:\program files\python311\lib\site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client<3.0.0,>=2.108.0->skipy) (4.25.6)
Collecting proto-plus<2.0.0,>=1.22.3
  Downloading proto_plus-1.26.1-py3-none-any.whl (50 kB)
     ---------------------------------------- 50.2/50.2 kB ? eta 0:00:00
Collecting cachetools<6.0,>=2.0.0
  Downloading cachetools-5.5.2-py3-none-any.whl (10 kB)
Collecting pyasn1-modules>=0.2.1
  Downloading pyasn1_modules-0.4.2-py3-none-any.whl (181 kB)
     ------------------------------------- 181.3/181.3 kB 11.4 MB/s eta 0:00:00
Collecting rsa<5,>=3.1.4
  Downloading rsa-4.9.1-py3-none-any.whl (34 kB)
Collecting pyparsing!=3.0.0,!=3.0.1,!=3.0.2,!=3.0.3,<4,>=2.4.2
  Downloading pyparsing-3.2.3-py3-none-any.whl (111 kB)
     ---------------------------------------- 111.1/111.1 kB ? eta 0:00:00
Requirement already satisfied: attrs>=23.2.0 in c:\program files\python311\lib\site-packages (from trio~=0.17->selenium<5.0.0,>=4.15.2->skipy) (25.3.0)
Collecting sortedcontainers
  Downloading sortedcontainers-2.4.0-py2.py3-none-any.whl (29 kB)
Collecting outcome
  Downloading outcome-1.3.0.post0-py2.py3-none-any.whl (10 kB)
Requirement already satisfied: sniffio>=1.3.0 in c:\program files\python311\lib\site-packages (from trio~=0.17->selenium<5.0.0,>=4.15.2->skipy) (1.3.1)
Requirement already satisfied: cffi>=1.14 in c:\program files\python311\lib\site-packages (from trio~=0.17->selenium<5.0.0,>=4.15.2->skipy) (1.17.1)
Collecting wsproto>=0.14
  Downloading wsproto-1.2.0-py3-none-any.whl (24 kB)
Collecting pysocks!=1.5.7,<2.0,>=1.5.6
  Downloading PySocks-1.7.1-py3-none-any.whl (16 kB)
Requirement already satisfied: pycparser in c:\program files\python311\lib\site-packages (from cffi>=1.14->trio~=0.17->selenium<5.0.0,>=4.15.2->skipy) (2.22)
Collecting pyasn1<0.7.0,>=0.6.1
  Downloading pyasn1-0.6.1-py3-none-any.whl (83 kB)
     ---------------------------------------- 83.1/83.1 kB 2.4 MB/s eta 0:00:00
Requirement already satisfied: six>=1.5 in c:\program files\python311\lib\site-packages (from python-dateutil<3.0.0,>=2.1->botocore<1.39.0,>=1.38.7->boto3<2.0.0,>=1.29.6->skipy) (1.17.0)
Requirement already satisfied: h11<1,>=0.9.0 in c:\program files\python311\lib\site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium<5.0.0,>=4.15.2->skipy) (0.14.0)
Installing collected packages: sortedcontainers, wsproto, uritemplate, slack-sdk, python-magic, pysocks, pyparsing, pyasn1, proto-plus, outcome, jmespath, cachetools, trio, rsa, pyasn1-modules, httplib2, botocore, trio-websocket, s3transfer, google-auth, selenium, google-auth-httplib2, google-api-core, boto3, google-api-python-client, skipy
Successfully installed boto3-1.38.7 botocore-1.38.7 cachetools-5.5.2 google-api-core-2.24.2 google-api-python-client-2.169.0 google-auth-2.39.0 google-auth-httplib2-0.2.0 httplib2-0.22.0 jmespath-1.0.1 outcome-1.3.0.post0 proto-plus-1.26.1 pyasn1-0.6.1 pyasn1-modules-0.4.2 pyparsing-3.2.3 pysocks-1.7.1 python-magic-0.4.27 rsa-4.9.1 s3transfer-0.12.0 selenium-4.31.0 skipy-0.2.3 slack-sdk-3.35.0 sortedcontainers-2.4.0 trio-0.30.0 trio-websocket-0.12.2 uritemplate-4.1.1 wsproto-1.2.0
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip available: 22.3 -> 25.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [196]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 816 entries, 0 to 815
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               816 non-null    int64
 1   city             803 non-null    object
 2   date             816 non-null    object
 3   player_of_match  812 non-null    object
 4   venue            816 non-null    object
 5   neutral_venue    816 non-null    int64
 6   team1            816 non-null    object
 7   team2            816 non-null    object
 8   toss_winner      816 non-null    object
 9   toss_decision    816 non-null    object
 10  winner           812 non-null    object
 11  result           812 non-null    object
 12  result_margin    799 non-null    float64
 13  eliminator       812 non-null    object
 14  method           19 non-null     object
 15  umpire1          816 non-null    object
 16  umpire2          816 non-null    object
dtypes: float64(1), int64(2), object(14)
memory usage: 108.5+ KB

In [197]:
df.isnull().sum()

id                   0
city                13
date                 0
player_of_match      4
venue                0
neutral_venue        0
team1                0
team2                0
toss_winner          0
toss_decision        0
winner               4
result               4
result_margin       17
eliminator           4
method             797
umpire1              0
umpire2              0
dtype: int64